require('lims-laboratory-app/laboratory/tube_rack/create_tube_rack')
require('lims-laboratory-app/laboratory/tube_rack/tube_rack_move')
require('lims-laboratory-app/laboratory/tube_rack/tube_rack_persistor')
require('lims-laboratory-app/laboratory/tube_rack/tube_rack_transfer')
require('lims-laboratory-app/laboratory/tube_rack/update_tube_rack')
require('lims-laboratory-app/laboratory/tube_rack/delete_tube_rack')
require('lims-laboratory-app/laboratory/tube_rack')
require('lims-laboratory-app/laboratory')
