require('lims-laboratory-app/laboratory/container/container')
require('lims-laboratory-app/laboratory/container/container_element_persistor')
require('lims-laboratory-app/laboratory/container/container_element_sequel_persistor')
require('lims-laboratory-app/laboratory/container/container_persistor')
require('lims-laboratory-app/laboratory/container/container_sequel_persistor')
require('lims-laboratory-app/laboratory/container')
