development:
  adapter: sqlite
  database: dev.db

test__:
  adapter: sqlite
  database: test.db

development_mysql:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: laboratory_development
  username: root
  password: root
  socket: /tmp/mysql.sock

test_mysql:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: laboratory_test
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: jdbc
  url: mysql://localhost/laboratory_test?user=root
  charset: utf8
  encoding: utf8
