require 'lims-laboratory-app/laboratory/plate/all'
require 'lims-laboratory-app/laboratory/gel/all'
require 'lims-laboratory-app/laboratory/tube/all'
require 'lims-laboratory-app/laboratory/tube_rack/all'
require 'lims-laboratory-app/laboratory/spin_column/all'
require 'lims-laboratory-app/laboratory/flowcell/all'

require 'lims-laboratory-app/laboratory/aliquot/all'
require 'lims-laboratory-app/laboratory/sample/all'
require 'lims-laboratory-app/laboratory/oligo/all'
require 'lims-laboratory-app/laboratory/tag_group/all'
