require('lims-laboratory-app/laboratory/plate/create_plate')
require('lims-laboratory-app/laboratory/plate/plate_persistor')
require('lims-laboratory-app/laboratory/plate/plate_sequel_persistor')
require('lims-laboratory-app/laboratory/plate/plate_transfer')
require('lims-laboratory-app/laboratory/plate/transfer_plates_to_plates')
require('lims-laboratory-app/laboratory/plate/update_plate')
require('lims-laboratory-app/laboratory/plate')
require('lims-laboratory-app/laboratory/receptacle')
